.PHONY: clean All

All:
	@echo "----------Building project:[ CppStyleStrings - Debug ]----------"
	@cd "CppStyleStrings" && "$(MAKE)" -f  "CppStyleStrings.mk"
clean:
	@echo "----------Cleaning project:[ CppStyleStrings - Debug ]----------"
	@cd "CppStyleStrings" && "$(MAKE)" -f  "CppStyleStrings.mk" clean
