.PHONY: clean All

All:
	@echo "----------Building project:[ C-styleStrings - Debug ]----------"
	@cd "C-styleStrings" && "$(MAKE)" -f  "C-styleStrings.mk"
clean:
	@echo "----------Cleaning project:[ C-styleStrings - Debug ]----------"
	@cd "C-styleStrings" && "$(MAKE)" -f  "C-styleStrings.mk" clean
