.PHONY: clean All

All:
	@echo "----------Building project:[ Sec10_Assignment_LetterPyramid - Debug ]----------"
	@cd "Sec10_Assignment_LetterPyramid" && "$(MAKE)" -f  "Sec10_Assignment_LetterPyramid.mk"
clean:
	@echo "----------Cleaning project:[ Sec10_Assignment_LetterPyramid - Debug ]----------"
	@cd "Sec10_Assignment_LetterPyramid" && "$(MAKE)" -f  "Sec10_Assignment_LetterPyramid.mk" clean
