.PHONY: clean All

All:
	@echo "----------Building project:[ Section_8_Exercise - Debug ]----------"
	@cd "Section_8_Exercise" && "$(MAKE)" -f  "Section_8_Exercise.mk"
clean:
	@echo "----------Cleaning project:[ Section_8_Exercise - Debug ]----------"
	@cd "Section_8_Exercise" && "$(MAKE)" -f  "Section_8_Exercise.mk" clean
