.PHONY: clean All

All:
	@echo "----------Building project:[ EqualityTesting - Debug ]----------"
	@cd "EqualityTesting" && "$(MAKE)" -f  "EqualityTesting.mk"
clean:
	@echo "----------Cleaning project:[ EqualityTesting - Debug ]----------"
	@cd "EqualityTesting" && "$(MAKE)" -f  "EqualityTesting.mk" clean
