.PHONY: clean All

All:
	@echo "----------Building project:[ Section_6_Exercise - Debug ]----------"
	@cd "Section_6_Exercise" && "$(MAKE)" -f  "Section_6_Exercise.mk"
clean:
	@echo "----------Cleaning project:[ Section_6_Exercise - Debug ]----------"
	@cd "Section_6_Exercise" && "$(MAKE)" -f  "Section_6_Exercise.mk" clean
