.PHONY: clean All

All:
	@echo "----------Building project:[ FranksCarpetCleaningEstimate - Debug ]----------"
	@cd "FranksCarpetCleaningEstimate" && "$(MAKE)" -f  "FranksCarpetCleaningEstimate.mk"
clean:
	@echo "----------Cleaning project:[ FranksCarpetCleaningEstimate - Debug ]----------"
	@cd "FranksCarpetCleaningEstimate" && "$(MAKE)" -f  "FranksCarpetCleaningEstimate.mk" clean
