.PHONY: clean All

All:
	@echo "----------Building project:[ Section_4_Challenge - Debug ]----------"
	@cd "Section_4_Challenge" && "$(MAKE)" -f  "Section_4_Challenge.mk"
clean:
	@echo "----------Cleaning project:[ Section_4_Challenge - Debug ]----------"
	@cd "Section_4_Challenge" && "$(MAKE)" -f  "Section_4_Challenge.mk" clean
