.PHONY: clean All

All:
	@echo "----------Building project:[ 107_Overloading_Functions - Debug ]----------"
	@cd "107_Overloading_Functions" && "$(MAKE)" -f  "107_Overloading_Functions.mk"
clean:
	@echo "----------Cleaning project:[ 107_Overloading_Functions - Debug ]----------"
	@cd "107_Overloading_Functions" && "$(MAKE)" -f  "107_Overloading_Functions.mk" clean
