.PHONY: clean All

All:
	@echo "----------Building project:[ 108_Passing_Arrays_to_Functions - Debug ]----------"
	@cd "108_Passing_Arrays_to_Functions" && "$(MAKE)" -f  "108_Passing_Arrays_to_Functions.mk"
clean:
	@echo "----------Cleaning project:[ 108_Passing_Arrays_to_Functions - Debug ]----------"
	@cd "108_Passing_Arrays_to_Functions" && "$(MAKE)" -f  "108_Passing_Arrays_to_Functions.mk" clean
