.PHONY: clean All

All:
	@echo "----------Building project:[ Exercise_22_Functions_and_Prototypes - Debug ]----------"
	@cd "Exercise_22_Functions_and_Prototypes" && "$(MAKE)" -f  "Exercise_22_Functions_and_Prototypes.mk"
clean:
	@echo "----------Cleaning project:[ Exercise_22_Functions_and_Prototypes - Debug ]----------"
	@cd "Exercise_22_Functions_and_Prototypes" && "$(MAKE)" -f  "Exercise_22_Functions_and_Prototypes.mk" clean
