.PHONY: clean All

All:
	@echo "----------Building project:[ Section9Exercises - Debug ]----------"
	@cd "Section9Exercises" && "$(MAKE)" -f  "Section9Exercises.mk"
clean:
	@echo "----------Cleaning project:[ Section9Exercises - Debug ]----------"
	@cd "Section9Exercises" && "$(MAKE)" -f  "Section9Exercises.mk" clean
